// AUTO-GENERATED by scripts/sync_dashboard.py

import type { Stats } from "./types";

export const stats: Stats = {
  hero: {
    versions: 12,
    outputs: 17,
    categories: 5,
    currentVersion: "v0.7.1",
  },
};

export const kpiBlocks = [
  { label: "调研产出", value: 17, suffix: "个" },
  { label: "版本迭代", value: 12, suffix: "个" },
  { label: "主体分类", value: 5, suffix: "类" },
  { label: "当前版本", value: "v0.7.1", suffix: "" },
] as const;

export const systemFeatures = [
  {
    title: "多步骤工作流",
    description: "13 个源码模块化的调研流程，从意图挖掘到读者模拟的完整链路",
  },
  {
    title: "意图挖掘",
    description: "从用户描述中反推真实问题，不是直接回答表面问题",
  },
  {
    title: "读者模拟",
    description: "AI 写完后换角色当读者自检，模拟真实读者的理解过程",
  },
  {
    title: "版本回退",
    description: "从 v0.10 过度工程化回退到 v0.5 做减法，保留核心流程",
  },
];

export const systemDefinition =
  "一套个人调研系统，用多步骤工作流替代单次对话，让 AI 同时当作者和读者，产出可交付的 HTML 报告。";
