// AUTO-GENERATED by scripts/sync_dashboard.py

import type { Version } from "./types";

export const versions: Version[] = [
  {
    id: "v0.7.1",
    date: "- 2026-07-05",
    summary: "**`validate_research_project.py` 的 `check_core_object_mentions`**：从硬编码 `[\"MuseDAM\", \"atypica\", \"GEA\", \"System of Context\"]` 改为从 `task-card.md` 的 `## 核心对象` 章节读取 Agent 声明的列表。工具不硬编码项目特定信息。",
    changes: ["**`final_report_writer.py` 的 `build_rewrite_instructions`**：删除 `action` 分类（原来用 `score < 0.3 → action = \"rewrite\"` 是语义判断）。改为只输出 `data_for_agent`（booleans + counts），action 决策由 Agent 做。", "**`README.md`**：从 v0.5 重写到 v0.7.1，加入 Smart Agent Dumb Tools 设计哲学、v0.7 7 项检查摘要、v0.6 三大模块说明、发布完整性条款", "**`templates/00-使用说明.md`**：从 v0.5 完全重写到 v0.7.1，包含 v0.6/v0.7/v0.7.1 全部新内容", "**`archive/README.md`**：从 v0.5 同步到 v0.7.1", "**所有模板文件的 `ros-version` 头**：统一从 v0.5/v0.6 升级到 v0.7.1"],
    isCurrent: true,
  },
  {
    id: "v0.7",
    date: "- 2026-07-05",
    summary: "命令行参数支持任意项目路径",
    changes: ["动态可视化组件识别（基于关键词模式匹配）", "固化美学规范（从 `09-HTML美学规范.md` 读取，不在代码里硬编码）", "修复 v0.6 的滚轮 bug（aside.toc overflow: hidden）", "修复 v0.6 的附录 div 闭合 bug", "结构化重写指令（`rewrite_instructions.json`）", "迭代状态追踪（`iteration_state.json`）", "最多 2 轮迭代，第 3 轮 fail 让人接手", "从 15 步线性流程升级为 15 步 + 5 个强制门禁", "加入 step 6.5 核心对象直采（强制门禁）", "加入 step 9.5 独立审计（强制门禁，5 问全 PASS）", "加入 step 10.5 写-读-改闭环（强制门禁，max 2 轮）", "加入 HTML 禁止模式检查（强制门禁）", "`templates/16-独立审计Agent.md`：独立审计 Agent 协议", "`templates/17-核心对象直采协议.md`：核心对象直采协议", "`templates/18-核心对象直采模板.md`：核心对象直采模板", "在特赞项目上验证：38 PASS / 1 WARN / 16 FAIL，发现 14 个 v0.6.1 漏检问题", "HTML v0.7 构建器验证：无禁止模式警告", "写-读-改闭环验证：通过，overall_score=0.85"],
  },
  {
    id: "v0.6",
    date: "- 2026-07-04",
    summary: "**独立审计 Agent**（步骤 9.5，强制门禁，5 问全 PASS）",
    changes: ["由独立会话的审计 Agent 执行", "不知道调研过程，只看产物", "5 个问题全 PASS 才能进入步骤 10", "**核心对象直采协议**（步骤 6.5，强制门禁）", "core_objects_fetch_log.md 必须存在", "URL >= 3 + 对象 >= 3 + 字符数 >= 200", "前置：步骤 2 和 3 必须 done", "**写-读-改闭环**（步骤 10.5）", "reader_simulation.py 模拟读者", "final_report_writer.py 根据读者反馈重写", "最多 2 轮迭代", "**Smart Agent. Dumb Tools.** 原则确立", "工具只做机械检查（存在性、字数、格式、字段值非空）", "语义判断（好不好、要不要重写、质量高低）交给 Agent", "分权制衡：调研 Agent（生产权）/ 审计 Agent（验证权）/ 工具（记录权）", "`templates/08-最终报告.md`：升级到 v0.6（加入核心对象直采引用要求）", "`templates/16-独立审计Agent.md`", "`templates/17-核心对象直采协议.md`", "`templates/18-核心对象直采模板.md`"],
  },
  {
    id: "v0.5",
    date: "- 2026-07-04",
    summary: "统一版本号到 v0.5，废弃 v0.1-v0.10 的碎片化版本号",
    changes: ["`00-使用说明.md` 完全重写（v0.1 到 v0.5，同步到系统真实状态）", "`create_research_project.py` 完全重写（v0.1 到 v0.5）", "`14-研究执行状态机.md` 重写（v0.4 到 v0.5）", "**`09-HTML美学规范.md`**：从 `build_research_html.py` 的 CSS（v0.8 + v0.9.1 + v0.9.2 + v0.10）抽取并固化为独立文档。这是 HTML 视觉规格的**单一真相源**。", "**`archive/` 目录**：所有 `.bak` 文件归档于此，明确标注\"不作为当前规范\"。", "**`archive/README.md`**：说明归档规则。", "**`CHANGELOG.md`**：本文件，版本变更记录。", "每个文件头加 `<!-- ros-version: v0.5 | last-updated: YYYY-MM-DD | status: current -->` 版本标记。", "**`create_research_project.py`**：", "从复制 5 个模板扩展到复制 14 个模板", "初始化 `candidates.md` + `discarded.md`（不只是 `candidate_pool.json`）", "初始化 `intent_doc.json` + `goal_ledger.json`", "schema_version 升级到 v0.5", "状态机加入完整 15 步流程状态", "加入 3 个人工确认点标记", "**`14-研究执行状态机.md`**：", "从 12 步线性流程升级为 15 步 + 写-读-改闭环", "加入 step 0 scaffold / step 7 analysis / step 10 reader_simulation / step 15 publish", "加入 3 个人工确认点", "加入版本一致性质量底线", "加入 HTML 美学合规质量底线", "`00-使用说明.md` v0.1 到 `archive/v0.1/`", "`01-调研任务卡.md.v07.bak` 到 `archive/v0.7/`", "`intent_discovery.py.v08.bak` 到 `archive/v0.8/`", "`research_router.py.v08.bak` 到 `archive/v0.8/`", "`validate_research_project.py.v08.bak` 到 `archive/v0.8/`", "`build_research_html.py.v09.bak` 到 `archive/v0.9/`", "`build_research_html.py.v091.bak` 到 `archive/v0.9/`", "`13-假设账本.md` v0.3 到 `archive/v0.9/13-假设账本.md.v0.3.bak`", "`_call_deepseek.py` 到 `archive/misc/`"],
    isRollback: true,
  },
  {
    id: "v0.10",
    date: "- 2026-07-03（已归档）",
    summary: "引入 `reader_simulation.py` 写-读-改闭环",
    changes: ["`final_report_writer.py` 支持 5 幕叙事", "`intent_discovery.py` 加入意图探索", "`concept_ladder_helper.py` 术语阶梯", "`build_research_html.py` CSS v0.10"],
  },
  {
    id: "v0.9",
    date: "- 2026-07-02（已归档）",
    summary: "`build_research_html.py` CSS v0.9.1 + v0.9.2",
    changes: ["`intent_discovery.py` v0.9", "`research_router.py` v0.9", "`04-假设账本.md` v0.9（融入 ljg-think drill_down）"],
  },
  {
    id: "v0.8",
    date: "- 2026-07-01（已归档）",
    summary: "`build_research_html.py` CSS v0.8（Anthropic cream + Lora + Starlight asides）",
    changes: ["`intent_discovery.py` v0.8", "`research_router.py` v0.8", "`validate_research_project.py` v0.8"],
  },
  {
    id: "v0.7",
    date: "- 2026-06-30（已归档）",
    summary: "`research_planner.py` v0.7",
    changes: ["`validate_research_project.py` v0.7", "`goal_tracker.py` v0.7", "`iteration_log.py` v0.7"],
  },
  {
    id: "v0.4",
    date: "- 2026-06-26（已归档）",
    summary: "`14-研究执行状态机.md` v0.4（12 步线性流程）",
    changes: ["`15-结论溯源清单.md` v0.4", "`research_run_step.py` v0.4"],
  },
  {
    id: "v0.3",
    date: "- 2026-06-25（已归档）",
    summary: "`research_status.py` v0.3",
    changes: ["`research_planner.py` v0.3", "`validate_research_project.py` v0.3", "`13-假设账本.md` v0.3（已归档，被 04 取代）", "`12-候选池.md` v0.3"],
  },
  {
    id: "v0.2",
    date: "- 2026-06-24（已归档）",
    summary: "`09-可视化视图模型.md` v0.2",
    changes: [],
  },
  {
    id: "v0.1",
    date: "- 2026-06-22（已归档）",
    summary: "`00-使用说明.md` v0.1（Dify 时代，已归档）",
    changes: ["`create_research_project.py` v0.1（已重写为 v0.5）", "`research_status.py` v0.3", "`config.py` v0.1", "`ros.py` v0.1（CLI 入口）", "`llm_client.py` v0.1", "`research_planner.py` v0.1", "`research_router.py` v0.1", "`research_run_step.py` v0.1", "`validate_research_project.py` v0.1", "`build_research_html.py` v0.1", "5 个核心模板：00-使用说明 / 01-调研任务卡 / 02-调研方案 / 03-证据矩阵 / 04-假设账本", "R0/R1/R2/R3 深度档位定义", "8 种调研类型：company-jd / product / user-research / industry / competitor / topic / portfolio / mixed"],
  },
];
