// AUTO-GENERATED by scripts/sync_dashboard.py

import type { Version } from "./types";

export const versions: Version[] = [
  {
    id: "v1.3",
    date: "- 2026-07-12",
    summary: "\"可跳过\"是工程问题：结构化字段缺失，验证器无法检测\"是否执行了确认\"",
    changes: ["\"可糊弄\"是语义问题：即使有字段，Agent 也能填入浅层内容通过检查", "单纯的结构化字段只能解决\"可跳过\"，无法解决\"可糊弄\"", "新增 `templates/20-方向选择协议.md`", "Agent 给出 2-3 个方向，用户选择 + 修正", "比完整方案确认更便宜，更早纠偏", "产物：`00-task/direction_selection.json`", "R2/R3 强制，R0/R1 可跳过", "`STEP_ARTIFACTS` 新增 `step_1_5_direction_selection` 和 `step_9_6_adversarial_review`", "`STEP_DEPENDENCIES` 新增依赖链：step_2 依赖 step_1_5，step_10 依赖 step_9_6", "`JSON_FIELD_REQUIREMENTS` 新增 `first_principles_decomposition: list`", "新增 7 个检查函数（方向选择/对抗审核/第一性原理报告层/第一性原理意图层/人工确认强制/审计结构化/反方结构化）", "新增 `templates/21-对抗式审核协议.md`", "核心设计原理：**对抗比评判容易**", "subagent 不需要比主 Agent 更聪明，只需要能打破它的论点", "Context 隔离：对抗审核 subagent 只收到 final-report.md，不收到过程文件", "产物：`06-review/adversarial_review.json`", "验证规则：≥3 攻击 + 每个攻击有回应 + 含 first_principles 类型攻击", "新增 `templates/22-第一性原理拆解协议.md`", "三层结构：", "意图层：`intent_doc.json` 的 `first_principles_decomposition` 字段（≥3 条不可再分的底层逻辑）", "任务层：调研方案的元问题必填", "报告层：final-report.md 的\"第一性原理\"章节必填", "\"再分测试\"：subagent 对每条\"不可再分\"的原理尝试\"再分\"，如果能再分则不是真第一性原理", "补全 `templates/19-产品深度拆解标准.md`（v1.2 时是 placeholder）", "`intent_discovery.py`：Round 3 prompt 新增第 7 项 first_principles_decomposition 要求", "`finalize_exploration` 函数新增 `first_principles_decomposition` 参数", "`templates/14-研究执行状态机.md`：15 步 → 17 步，6 门禁 → 7 门禁", "`templates/08-最终报告.md`：新增 §2.5 第一性原理章节模板", "`templates/02-调研方案.md`：元问题标注为 v1.3 必填+验证", "增强独立审计检查：从\"PASS 字符串\"升级为\"5 问结构化检查\"", "增强反方审计检查：从\"字符数\"升级为\"攻击次数 + 降级次数\"", "5 个 FAIL 都是预期中的（现有项目缺少 v1.3 新增产物）", "新检查函数本身运行正常", "v1.2 之前：Smart Agent. Dumb Tools.（工具只做机械检查）", "v1.3 增强：结构化字段解决\"可跳过\"问题 + 对抗测试解决\"可糊弄\"问题", "不改变\"Dumb Tools\"原则——对抗测试仍是机械的（检查攻击次数、回应存在性）", ""],
    isCurrent: true,
  },
  {
    id: "v1.2",
    date: "- 2026-07-11",
    summary: "intent_doc.json 的 concept_ladder_seed 经常为空（Agent 跳过 Round 3 填充）",
    changes: ["reader_model 为空导致 reader_simulation 退化为默认画像", "验证器注释承诺\"术语解释数检查\"但未实现", "plain_glossary.py（20+ 术语库）完全孤立，未被任何流程引用", "`check_concept_ladder_seed`：seed >= 3 个术语", "`check_reader_model`：reader_model.background 非空", "`check_term_explanation_coverage`：seed 中每个术语在报告首次出现位置附近有解释标记", "合并 10 个孤立术语到 GLOSSARY 统一为 6 层结构", "消除了 plain_glossary.py 的孤立状态", "填充 concept_ladder_seed（10 个术语：GTM/ICP/Waterfall Enrichment 等）", "填充 reader_model（background + knowledge_blindspots + comprehension_target）", ""],
  },
  {
    id: "v1.1",
    date: "- 2026-07-10",
    summary: "修复规范与实现断层：恢复 HTML 构建器，验证器增加 9 项必须结构检查",
    changes: ["恢复 build_html_v07.py 到根目录，步骤 13 真正工具驱动，不再手写 HTML", "验证器新增 9 项 HTML 必须结构检查（page-shell/aside.toc/vm-hero/section.chapter 等）", "修复 Smart Agent Dumb Tools 哲学盲区：工具从只检查禁止什么扩展到也检查必须有什么", "使用说明重写为 v1.1，新增错误 11（手写HTML）和错误 12（规范引用已归档工具）"],
  },
  {
    id: "v1.0",
    date: "- 2026-07-09",
    summary: "新增行动方案比例检查和 LaTeX 公式渲染检查，但使用说明未同步",
    changes: ["新增 view-model reader-facing 检查：确保 hero 字段面向读者", "新增行动方案比例检查：最终报告中行动方案占比 ≥ 15%", "新增 LaTeX 公式渲染检查：报告含公式时 HTML 必须有 MathJax/KaTeX", "已知问题：build_html_v07.py 被误归档但使用说明仍引用（v1.1 已修复）"],
  },
  {
    id: "v0.7.1",
    date: "- 2026-07-05",
    summary: "去除工具中的项目硬编码，让系统真正通用化，建立发布完整性条款",
    changes: ["去除工具中的项目特定硬编码（如公司名列表），改为从任务卡动态读取", "去除工具中的语义判断逻辑，只输出数据，让 AI Agent 做决策", "同步所有入口文档到 v0.7.1（README / 使用说明 / 模板版本头）", "建立发布完整性条款：每次版本升级必须同步入口文档，杜绝文档滞后"],
  },
  {
    id: "v0.7",
    date: "- 2026-07-05",
    summary: "质量门禁从概念落地为可执行规则，新增 7 项机械检查",
    changes: ["从 15 步线性流程升级为 15 步 + 5 个强制门禁的体系", "新增 7 项机械检查：JSON 字段非空 / 步骤依赖 / 内容深度 / HTML 禁止模式等", "HTML 构建器通用化：支持任意项目路径，不再硬编码项目信息", "美学规范固化：从代码硬编码改为从文档读取，便于维护", "在特赞项目上验证：发现 14 个 v0.6 漏检问题，门禁体系有效"],
  },
  {
    id: "v0.6",
    date: "- 2026-07-04",
    summary: "确立 Smart Agent Dumb Tools 核心设计哲学，引入三大强制质量门禁",
    changes: ["确立 'Smart Agent Dumb Tools' 核心哲学：工具只做机械检查，语义判断交给 AI", "引入独立审计 Agent 门禁：由独立会话的 AI 复核调研产物，5 问全 PASS 才能继续", "引入核心对象直采协议：强制直接采访调研对象，不能只靠二手资料", "引入写-读-改闭环：AI 写完后换角色当读者自检，发现表达不清的地方", "建立分权制衡：调研 Agent（生产权）/ 审计 Agent（验证权）/ 工具（记录权）"],
  },
  {
    id: "v0.5",
    date: "- 2026-07-04",
    summary: "从 v0.10 过度工程化回退做减法，确立 15 步流程的完整调研骨架",
    changes: ["统一碎片化版本号（v0.1-v0.10 散落各处），全部归到 v0.5", "归档所有历史 .bak 文件到 archive/ 目录，主目录保持干净", "确立 15 步流程 + 3 个人工确认点的完整调研骨架", "HTML 美学规范从代码中抽取为独立文档，成为视觉规格的单一真相源", "脚手架从复制 5 个模板扩展到 14 个模板"],
    isRollback: true,
  },
  {
    id: "v0.10",
    date: "- 2026-07-03（已归档）",
    summary: "引入读者模拟闭环：AI 写完后换角色当读者自检",
    changes: ["引入读者模拟机制：AI 写完后换角色当读者，模拟真实读者的理解过程", "支持 5 幕叙事结构，让调研报告具备故事性", "引入术语阶梯工具，让专业术语有递进解释，非专业读者也能理解"],
  },
  {
    id: "v0.9",
    date: "- 2026-07-02（已归档）",
    summary: "引入意图探索机制，AI 在调研前先深挖用户真实问题",
    changes: ["引入意图探索机制：从用户描述中反推真实问题，避免答非所问", "引入 ljg-think drill_down 思维工具，让 AI 一层层钻到问题本质", "升级研究路由和意图发现模块，让调研方向更精准"],
  },
  {
    id: "v0.8",
    date: "- 2026-07-01（已归档）",
    summary: "引入 Anthropic 暖白美学，HTML 报告从工具产物升级为设计品",
    changes: ["引入 Anthropic 暖白配色（cream 背景 + 深文 + 橙色高亮）", "引入 Lora 衬线字体用于引述和强调，建立字体双轨制", "引入 Starlight asides 引述样式，让重点内容有视觉强调", "HTML 报告具备品牌识别度，不再是干瘪的工具产物"],
  },
  {
    id: "v0.7",
    date: "- 2026-06-30（已归档）",
    summary: "研究规划工具升级，让调研方向更精准",
    changes: ["升级研究规划工具，让调研方向选择更精准", "升级目标追踪和迭代日志工具"],
  },
  {
    id: "v0.4",
    date: "- 2026-06-26（已归档）",
    summary: "12 步线性调研流程成型，加入结论溯源清单",
    changes: ["确立 12 步线性调研流程：从任务定义到最终发布的完整链路", "加入结论溯源清单，让每个结论都能追溯到具体证据", "Claude Code 时代的最后一个版本，后续进入 Trae 时代"],
  },
  {
    id: "v0.3",
    date: "- 2026-06-25（已归档）",
    summary: "加入状态追踪和候选池管理，让调研过程可追溯、可监控",
    changes: ["加入研究状态追踪，每一步调研的状态都被记录，可随时查看进度", "加入候选池管理，让候选资料有清晰的纳入和淘汰记录", "加入研究规划工具，让调研方向有章可循"],
  },
  {
    id: "v0.2",
    date: "- 2026-06-24（已归档）",
    summary: "引入可视化视图模型，HTML 报告从纯文字升级为图表化呈现",
    changes: ["建立可视化视图模型规范，定义调研报告中图表的类型和使用场景", "HTML 报告开始支持图表化呈现，让调研产物更易读"],
  },
  {
    id: "v0.1",
    date: "- 2026-06-22（已归档）",
    summary: "Research OS 诞生：确立 CLI 工具 + 模板化流程的基本形态",
    changes: ["确立 CLI 命令行工具作为系统入口，定义 4 种调研深度（R0/R1/R2/R3）", "建立 5 个核心模板：调研任务卡 / 调研方案 / 证据矩阵 / 假设账本 / 使用说明", "定义 8 种调研类型：产品拆解 / 行业赛道 / 用户调研 / 竞品 / 选题 / 作品集等", "让 AI 调研从单次对话升级为流程化作业"],
  },
];
